server:
  port: 8064

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
            - Path=/api/auth/**
            - Path=/api/admin/**
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie

    circuitbreaker:
      hystrix:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8065/eureka/
  instance:
    hostname: localhost

ribbon:
  eureka:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
