server:
  port: 8062

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
    username: postgres.tjnshocbunnqohvrnwuo
    password: taRKo5XbQembRmtj
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            handler: org.hibernate.type.descriptor.jdbc.LobStorageStrategy

  sql:
    init:
      mode: always  # or 'never' depending on your requirements
    schema:
      import:
        - classpath:/db/schema.sql  # Path to your schema initialization SQL file
    data:
      import:
        - classpath:/db/data.sql  # Path to your data initialization SQL file

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8065/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
