server:
  port: 8061

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
    username: postgres.avnafxmbyzdmwtehhaxp
    password: 27Bf4bWQ1bYtJBTa
    driver-class-name: org.postgresql.Driver
    hikari:
      # HikariCP-specific settings
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP
      connection-test-query: SELECT 1
      data-source-properties:
        prepareThreshold: 0

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 50
          prepare_sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql.BasicBinder: TRACE
          cache: info
          transaction: trace
      com:
        camcorderio:
          productservice: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8065/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      version: 1.0
      region: ap-south-1

management:
  endpoints:
    web:
      exposure:
        include: "*"

hibernate:
  cache:
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

jackson:
  serialization:
    write-dates-as-timestamps: false

postgresql:
  prepareThreshold: 0
