server:
  port: 8061

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
    username: postgres.avnafxmbyzdmwtehhaxp
    password: 27Bf4bWQ1bYtJBTa

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
