name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build user-service JAR
        run: |
          cd user-service
          mvn clean package -DskipTests
          mv target/user-service-*.jar target/user-service.jar
          cd ..

      - name: Build admin-service JAR
        run: |
          cd admin-service
          mvn clean package -DskipTests
          mv target/admin-service-*.jar target/admin-service.jar
          cd ..

      - name: Build product-service JAR
        run: |
          cd product-service
          mvn clean package -DskipTests
          mv target/product-service-*.jar target/product-service.jar
          cd ..

      - name: Build api-gateway JAR
        run: |
          cd api-gateway
          mvn clean package -DskipTests
          mv target/api-gateway-*.jar target/api-gateway.jar
          cd ..

      - name: Build service-discovery JAR
        run: |
          cd service-discovery
          mvn clean package -DskipTests
          mv target/service-discovery-*.jar target/service-discovery.jar
          cd ..

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and push user-service Docker image
        run: |
          cd user-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
          cd ..

      - name: Build and push admin-service Docker image
        run: |
          cd admin-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/admin-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/admin-service:latest
          cd ..

      - name: Build and push product-service Docker image
        run: |
          cd product-service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/product-service:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/product-service:latest
          cd ..

      - name: Build and push api-gateway Docker image
        run: |
          cd api-gateway
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:latest
          cd ..

      - name: Build and push service-discovery Docker image
        run: |
          cd service-discovery
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/service-discovery:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service-discovery:latest
          cd ..
